/****************************************************************************
 *
 *   Copyright (C) 2013-2021 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/dagar/git/PX4-Autopilot_upstream/msg/optical_flow.msg */


#include <px4_platform_common/px4_config.h>
#include <ucdr/microcdr.h>
#include <uORB/topics/optical_flow.h>
#include <uORB_microcdr/topics/optical_flow.h>


void serialize_optical_flow(ucdrBuffer *writer, const struct optical_flow_s *input, char *output, uint32_t *length)
{
    if (nullptr == writer || nullptr == input || nullptr == output || nullptr == length)
	return;

    ucdr_reset_buffer(writer);

    ucdr_serialize_uint64_t(writer, input->timestamp);
    ucdr_serialize_uint8_t(writer, input->sensor_id);
    ucdr_serialize_float(writer, input->pixel_flow_x_integral);
    ucdr_serialize_float(writer, input->pixel_flow_y_integral);
    ucdr_serialize_float(writer, input->gyro_x_rate_integral);
    ucdr_serialize_float(writer, input->gyro_y_rate_integral);
    ucdr_serialize_float(writer, input->gyro_z_rate_integral);
    ucdr_serialize_float(writer, input->ground_distance_m);
    ucdr_serialize_uint32_t(writer, input->integration_timespan);
    ucdr_serialize_uint32_t(writer, input->time_since_last_sonar_update);
    ucdr_serialize_uint16_t(writer, input->frame_count_since_last_readout);
    ucdr_serialize_int16_t(writer, input->gyro_temperature);
    ucdr_serialize_uint8_t(writer, input->quality);
    ucdr_serialize_float(writer, input->max_flow_rate);
    ucdr_serialize_float(writer, input->min_ground_distance);
    ucdr_serialize_float(writer, input->max_ground_distance);
    ucdr_serialize_uint8_t(writer, input->mode);

    (*length) = ucdr_buffer_length(writer);
}

void deserialize_optical_flow(ucdrBuffer *reader, struct optical_flow_s *output, const char *input)
{
    if (nullptr == reader || nullptr == output || nullptr == input)
	return;

    ucdr_reset_buffer(reader);

    ucdr_deserialize_uint64_t(reader, &output->timestamp);
    ucdr_deserialize_uint8_t(reader, &output->sensor_id);
    ucdr_deserialize_float(reader, &output->pixel_flow_x_integral);
    ucdr_deserialize_float(reader, &output->pixel_flow_y_integral);
    ucdr_deserialize_float(reader, &output->gyro_x_rate_integral);
    ucdr_deserialize_float(reader, &output->gyro_y_rate_integral);
    ucdr_deserialize_float(reader, &output->gyro_z_rate_integral);
    ucdr_deserialize_float(reader, &output->ground_distance_m);
    ucdr_deserialize_uint32_t(reader, &output->integration_timespan);
    ucdr_deserialize_uint32_t(reader, &output->time_since_last_sonar_update);
    ucdr_deserialize_uint16_t(reader, &output->frame_count_since_last_readout);
    ucdr_deserialize_int16_t(reader, &output->gyro_temperature);
    ucdr_deserialize_uint8_t(reader, &output->quality);
    ucdr_deserialize_float(reader, &output->max_flow_rate);
    ucdr_deserialize_float(reader, &output->min_ground_distance);
    ucdr_deserialize_float(reader, &output->max_ground_distance);
    ucdr_deserialize_uint8_t(reader, &output->mode);

}
