/****************************************************************************
 *
 *   Copyright (C) 2013-2021 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/dagar/git/PX4-Autopilot_upstream/msg/position_setpoint_triplet.msg */


#include <px4_platform_common/px4_config.h>
#include <ucdr/microcdr.h>
#include <uORB/topics/position_setpoint_triplet.h>
#include <uORB_microcdr/topics/position_setpoint_triplet.h>


void serialize_position_setpoint_triplet(ucdrBuffer *writer, const struct position_setpoint_triplet_s *input, char *output, uint32_t *length)
{
    if (nullptr == writer || nullptr == input || nullptr == output || nullptr == length)
	return;

    ucdr_reset_buffer(writer);

    ucdr_serialize_uint64_t(writer, input->timestamp);
    ucdr_serialize_uint64_t(writer, input->previous.timestamp);
    ucdr_serialize_bool(writer, input->previous.valid);
    ucdr_serialize_uint8_t(writer, input->previous.type);
    ucdr_serialize_float(writer, input->previous.vx);
    ucdr_serialize_float(writer, input->previous.vy);
    ucdr_serialize_float(writer, input->previous.vz);
    ucdr_serialize_bool(writer, input->previous.velocity_valid);
    ucdr_serialize_uint8_t(writer, input->previous.velocity_frame);
    ucdr_serialize_bool(writer, input->previous.alt_valid);
    ucdr_serialize_double(writer, input->previous.lat);
    ucdr_serialize_double(writer, input->previous.lon);
    ucdr_serialize_float(writer, input->previous.alt);
    ucdr_serialize_float(writer, input->previous.yaw);
    ucdr_serialize_bool(writer, input->previous.yaw_valid);
    ucdr_serialize_float(writer, input->previous.yawspeed);
    ucdr_serialize_bool(writer, input->previous.yawspeed_valid);
    ucdr_serialize_int8_t(writer, input->previous.landing_gear);
    ucdr_serialize_float(writer, input->previous.loiter_radius);
    ucdr_serialize_int8_t(writer, input->previous.loiter_direction);
    ucdr_serialize_float(writer, input->previous.acceptance_radius);
    ucdr_serialize_float(writer, input->previous.cruising_speed);
    ucdr_serialize_float(writer, input->previous.cruising_throttle);
    ucdr_serialize_bool(writer, input->previous.disable_weather_vane);
    ucdr_serialize_uint64_t(writer, input->current.timestamp);
    ucdr_serialize_bool(writer, input->current.valid);
    ucdr_serialize_uint8_t(writer, input->current.type);
    ucdr_serialize_float(writer, input->current.vx);
    ucdr_serialize_float(writer, input->current.vy);
    ucdr_serialize_float(writer, input->current.vz);
    ucdr_serialize_bool(writer, input->current.velocity_valid);
    ucdr_serialize_uint8_t(writer, input->current.velocity_frame);
    ucdr_serialize_bool(writer, input->current.alt_valid);
    ucdr_serialize_double(writer, input->current.lat);
    ucdr_serialize_double(writer, input->current.lon);
    ucdr_serialize_float(writer, input->current.alt);
    ucdr_serialize_float(writer, input->current.yaw);
    ucdr_serialize_bool(writer, input->current.yaw_valid);
    ucdr_serialize_float(writer, input->current.yawspeed);
    ucdr_serialize_bool(writer, input->current.yawspeed_valid);
    ucdr_serialize_int8_t(writer, input->current.landing_gear);
    ucdr_serialize_float(writer, input->current.loiter_radius);
    ucdr_serialize_int8_t(writer, input->current.loiter_direction);
    ucdr_serialize_float(writer, input->current.acceptance_radius);
    ucdr_serialize_float(writer, input->current.cruising_speed);
    ucdr_serialize_float(writer, input->current.cruising_throttle);
    ucdr_serialize_bool(writer, input->current.disable_weather_vane);
    ucdr_serialize_uint64_t(writer, input->next.timestamp);
    ucdr_serialize_bool(writer, input->next.valid);
    ucdr_serialize_uint8_t(writer, input->next.type);
    ucdr_serialize_float(writer, input->next.vx);
    ucdr_serialize_float(writer, input->next.vy);
    ucdr_serialize_float(writer, input->next.vz);
    ucdr_serialize_bool(writer, input->next.velocity_valid);
    ucdr_serialize_uint8_t(writer, input->next.velocity_frame);
    ucdr_serialize_bool(writer, input->next.alt_valid);
    ucdr_serialize_double(writer, input->next.lat);
    ucdr_serialize_double(writer, input->next.lon);
    ucdr_serialize_float(writer, input->next.alt);
    ucdr_serialize_float(writer, input->next.yaw);
    ucdr_serialize_bool(writer, input->next.yaw_valid);
    ucdr_serialize_float(writer, input->next.yawspeed);
    ucdr_serialize_bool(writer, input->next.yawspeed_valid);
    ucdr_serialize_int8_t(writer, input->next.landing_gear);
    ucdr_serialize_float(writer, input->next.loiter_radius);
    ucdr_serialize_int8_t(writer, input->next.loiter_direction);
    ucdr_serialize_float(writer, input->next.acceptance_radius);
    ucdr_serialize_float(writer, input->next.cruising_speed);
    ucdr_serialize_float(writer, input->next.cruising_throttle);
    ucdr_serialize_bool(writer, input->next.disable_weather_vane);

    (*length) = ucdr_buffer_length(writer);
}

void deserialize_position_setpoint_triplet(ucdrBuffer *reader, struct position_setpoint_triplet_s *output, const char *input)
{
    if (nullptr == reader || nullptr == output || nullptr == input)
	return;

    ucdr_reset_buffer(reader);

    ucdr_deserialize_uint64_t(reader, &output->timestamp);
    ucdr_deserialize_uint64_t(reader, &output->previous.timestamp);
    ucdr_deserialize_bool(reader, &output->previous.valid);
    ucdr_deserialize_uint8_t(reader, &output->previous.type);
    ucdr_deserialize_float(reader, &output->previous.vx);
    ucdr_deserialize_float(reader, &output->previous.vy);
    ucdr_deserialize_float(reader, &output->previous.vz);
    ucdr_deserialize_bool(reader, &output->previous.velocity_valid);
    ucdr_deserialize_uint8_t(reader, &output->previous.velocity_frame);
    ucdr_deserialize_bool(reader, &output->previous.alt_valid);
    ucdr_deserialize_double(reader, &output->previous.lat);
    ucdr_deserialize_double(reader, &output->previous.lon);
    ucdr_deserialize_float(reader, &output->previous.alt);
    ucdr_deserialize_float(reader, &output->previous.yaw);
    ucdr_deserialize_bool(reader, &output->previous.yaw_valid);
    ucdr_deserialize_float(reader, &output->previous.yawspeed);
    ucdr_deserialize_bool(reader, &output->previous.yawspeed_valid);
    ucdr_deserialize_int8_t(reader, &output->previous.landing_gear);
    ucdr_deserialize_float(reader, &output->previous.loiter_radius);
    ucdr_deserialize_int8_t(reader, &output->previous.loiter_direction);
    ucdr_deserialize_float(reader, &output->previous.acceptance_radius);
    ucdr_deserialize_float(reader, &output->previous.cruising_speed);
    ucdr_deserialize_float(reader, &output->previous.cruising_throttle);
    ucdr_deserialize_bool(reader, &output->previous.disable_weather_vane);
    ucdr_deserialize_uint64_t(reader, &output->current.timestamp);
    ucdr_deserialize_bool(reader, &output->current.valid);
    ucdr_deserialize_uint8_t(reader, &output->current.type);
    ucdr_deserialize_float(reader, &output->current.vx);
    ucdr_deserialize_float(reader, &output->current.vy);
    ucdr_deserialize_float(reader, &output->current.vz);
    ucdr_deserialize_bool(reader, &output->current.velocity_valid);
    ucdr_deserialize_uint8_t(reader, &output->current.velocity_frame);
    ucdr_deserialize_bool(reader, &output->current.alt_valid);
    ucdr_deserialize_double(reader, &output->current.lat);
    ucdr_deserialize_double(reader, &output->current.lon);
    ucdr_deserialize_float(reader, &output->current.alt);
    ucdr_deserialize_float(reader, &output->current.yaw);
    ucdr_deserialize_bool(reader, &output->current.yaw_valid);
    ucdr_deserialize_float(reader, &output->current.yawspeed);
    ucdr_deserialize_bool(reader, &output->current.yawspeed_valid);
    ucdr_deserialize_int8_t(reader, &output->current.landing_gear);
    ucdr_deserialize_float(reader, &output->current.loiter_radius);
    ucdr_deserialize_int8_t(reader, &output->current.loiter_direction);
    ucdr_deserialize_float(reader, &output->current.acceptance_radius);
    ucdr_deserialize_float(reader, &output->current.cruising_speed);
    ucdr_deserialize_float(reader, &output->current.cruising_throttle);
    ucdr_deserialize_bool(reader, &output->current.disable_weather_vane);
    ucdr_deserialize_uint64_t(reader, &output->next.timestamp);
    ucdr_deserialize_bool(reader, &output->next.valid);
    ucdr_deserialize_uint8_t(reader, &output->next.type);
    ucdr_deserialize_float(reader, &output->next.vx);
    ucdr_deserialize_float(reader, &output->next.vy);
    ucdr_deserialize_float(reader, &output->next.vz);
    ucdr_deserialize_bool(reader, &output->next.velocity_valid);
    ucdr_deserialize_uint8_t(reader, &output->next.velocity_frame);
    ucdr_deserialize_bool(reader, &output->next.alt_valid);
    ucdr_deserialize_double(reader, &output->next.lat);
    ucdr_deserialize_double(reader, &output->next.lon);
    ucdr_deserialize_float(reader, &output->next.alt);
    ucdr_deserialize_float(reader, &output->next.yaw);
    ucdr_deserialize_bool(reader, &output->next.yaw_valid);
    ucdr_deserialize_float(reader, &output->next.yawspeed);
    ucdr_deserialize_bool(reader, &output->next.yawspeed_valid);
    ucdr_deserialize_int8_t(reader, &output->next.landing_gear);
    ucdr_deserialize_float(reader, &output->next.loiter_radius);
    ucdr_deserialize_int8_t(reader, &output->next.loiter_direction);
    ucdr_deserialize_float(reader, &output->next.acceptance_radius);
    ucdr_deserialize_float(reader, &output->next.cruising_speed);
    ucdr_deserialize_float(reader, &output->next.cruising_throttle);
    ucdr_deserialize_bool(reader, &output->next.disable_weather_vane);

}
