/****************************************************************************
 *
 *   Copyright (C) 2013-2021 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/dagar/git/PX4-Autopilot_upstream/msg/position_setpoint.msg */


#include <px4_platform_common/px4_config.h>
#include <ucdr/microcdr.h>
#include <uORB/topics/position_setpoint.h>
#include <uORB_microcdr/topics/position_setpoint.h>


void serialize_position_setpoint(ucdrBuffer *writer, const struct position_setpoint_s *input, char *output, uint32_t *length)
{
    if (nullptr == writer || nullptr == input || nullptr == output || nullptr == length)
	return;

    ucdr_reset_buffer(writer);

    ucdr_serialize_uint64_t(writer, input->timestamp);
    ucdr_serialize_bool(writer, input->valid);
    ucdr_serialize_uint8_t(writer, input->type);
    ucdr_serialize_float(writer, input->vx);
    ucdr_serialize_float(writer, input->vy);
    ucdr_serialize_float(writer, input->vz);
    ucdr_serialize_bool(writer, input->velocity_valid);
    ucdr_serialize_uint8_t(writer, input->velocity_frame);
    ucdr_serialize_bool(writer, input->alt_valid);
    ucdr_serialize_double(writer, input->lat);
    ucdr_serialize_double(writer, input->lon);
    ucdr_serialize_float(writer, input->alt);
    ucdr_serialize_float(writer, input->yaw);
    ucdr_serialize_bool(writer, input->yaw_valid);
    ucdr_serialize_float(writer, input->yawspeed);
    ucdr_serialize_bool(writer, input->yawspeed_valid);
    ucdr_serialize_int8_t(writer, input->landing_gear);
    ucdr_serialize_float(writer, input->loiter_radius);
    ucdr_serialize_int8_t(writer, input->loiter_direction);
    ucdr_serialize_float(writer, input->acceptance_radius);
    ucdr_serialize_float(writer, input->cruising_speed);
    ucdr_serialize_float(writer, input->cruising_throttle);
    ucdr_serialize_bool(writer, input->disable_weather_vane);

    (*length) = ucdr_buffer_length(writer);
}

void deserialize_position_setpoint(ucdrBuffer *reader, struct position_setpoint_s *output, const char *input)
{
    if (nullptr == reader || nullptr == output || nullptr == input)
	return;

    ucdr_reset_buffer(reader);

    ucdr_deserialize_uint64_t(reader, &output->timestamp);
    ucdr_deserialize_bool(reader, &output->valid);
    ucdr_deserialize_uint8_t(reader, &output->type);
    ucdr_deserialize_float(reader, &output->vx);
    ucdr_deserialize_float(reader, &output->vy);
    ucdr_deserialize_float(reader, &output->vz);
    ucdr_deserialize_bool(reader, &output->velocity_valid);
    ucdr_deserialize_uint8_t(reader, &output->velocity_frame);
    ucdr_deserialize_bool(reader, &output->alt_valid);
    ucdr_deserialize_double(reader, &output->lat);
    ucdr_deserialize_double(reader, &output->lon);
    ucdr_deserialize_float(reader, &output->alt);
    ucdr_deserialize_float(reader, &output->yaw);
    ucdr_deserialize_bool(reader, &output->yaw_valid);
    ucdr_deserialize_float(reader, &output->yawspeed);
    ucdr_deserialize_bool(reader, &output->yawspeed_valid);
    ucdr_deserialize_int8_t(reader, &output->landing_gear);
    ucdr_deserialize_float(reader, &output->loiter_radius);
    ucdr_deserialize_int8_t(reader, &output->loiter_direction);
    ucdr_deserialize_float(reader, &output->acceptance_radius);
    ucdr_deserialize_float(reader, &output->cruising_speed);
    ucdr_deserialize_float(reader, &output->cruising_throttle);
    ucdr_deserialize_bool(reader, &output->disable_weather_vane);

}
