#
# Accelerometer readings and in-run biases in SI-unit form. Sensor readings are compensated for static offsets,
# scale errors, in-run bias and thermal drift (if thermal compensation is enabled and available).
#

float32 x		# Bias corrected acceleration in body X axis (in rad/s)
float32 y		# Bias corrected acceleration in body Y axis (in rad/s)
float32 z		# Bias corrected acceleration in body Z axis (in rad/s)
